const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const context={window:{}};vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(__dirname,'../web/financial-statements.js'),'utf8'),context);
const {amount,sourceText,esc,waterfallLabel,waterfallTickFormat,cashChangeText,shareText,balanceShare}=context.window.financialStatementFormat;
assert.equal(amount({value:0,unit:'元'}),'0.00 亿元');
assert.equal(amount({value:null,unit:'元'}),'待补');
assert.equal(amount({value:100000000,unit:'元'},'万元'),'10,000.00 万元');
assert.equal(amount({value:3.5,unit:'元/股'}),'3.50 元/股');
assert.equal(amount({value:50,unit:'%'}),'50.00 %');
assert.equal(esc('<script>"&'), '&lt;script&gt;&quot;&amp;');
assert.match(sourceText({source:'llb',field:'MANANETR',method:'本期累计 − 上季累计',period:'2025-06-30'}),/MANANETR/);
assert.equal(waterfallLabel('其他营业损益（净额）'),'其他营业损益<br>（净额）');
assert.equal(waterfallLabel('期初现金及等价物'),'期初现金及<br>现金等价物');
assert.equal(waterfallLabel('经营净现金流'),'经营活动<br>净现金流');
assert.equal(waterfallLabel('营业总收入'),'营业总收入');
assert.equal(waterfallLabel('<script>'),'&lt;scrip<br>t&gt;');
assert.equal(waterfallTickFormat([{value:2195e8,measure:'absolute'}],1e8),',.0~f');
assert.equal(waterfallTickFormat([{value:100,measure:'absolute'},{value:-250,measure:'relative'}],1e8),',.8~f');
assert.equal(waterfallTickFormat([{value:0,measure:'absolute'}],1e8),',.0~f');
assert.match(cashChangeText(150881601005.77,140837137657.52,'亿元'),/减少 100\.44 亿元（6\.66%）/);
assert.match(cashChangeText(100,120,'元'),/增加 20\.00 元（20\.00%）/);
assert.match(cashChangeText(100,100,'元'),/持平/);
assert.equal(cashChangeText(null,100,'元'),'');
assert.equal(cashChangeText(0,100,'元').includes('%'),false);
console.log('statement formatting checks passed');
assert.equal(shareText(0,200,'总负债'),'占总负债：0.00%');
assert.equal(shareText(null,200,'总负债'),'占总负债：待补');
assert.equal(shareText(25,0,'总负债'),'占总负债：待补');
const totals={assets:{value:500},liabilities:{value:200},equity:{value:300}};
assert.ok(Math.abs(balanceShare({value:140,balance_side:'assets'},totals).pct-28)<1e-10);
assert.equal(balanceShare({value:25,balance_side:'liabilities'},totals).pct,12.5);
assert.equal(balanceShare({value:300,balance_side:'equity'},totals).pct,100);
