const assert = require('node:assert/strict');
const fs = require('node:fs');

(async () => {
  const [port,base,desktopImage,mobileImage] = process.argv.slice(2);
  const targets = await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();
  const socket = new WebSocket(targets.find(target=>target.type==='page').webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject;});
  let sequence=0;const pending=new Map();
  socket.onmessage=event=>{const message=JSON.parse(event.data);const item=pending.get(message.id);if(item){pending.delete(message.id);message.error?item.reject(Error(message.error.message)):item.resolve(message.result);}};
  const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw Error(result.exceptionDetails.text+' '+JSON.stringify(result.exceptionDetails.exception));return result.result.value;};
  const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  const wait=async expression=>{for(let i=0;i<120;i++){if(await evaluate(expression))return;await sleep(25);}throw Error('Timed out: '+expression);};
  const idle=()=>wait('document.getElementById("stock-manage") && !document.getElementById("stock-manage").disabled');
  const read=async()=>(await fetch(base+'/api/stock-groups')).json();
  const click=async id=>{await evaluate(`document.getElementById(${JSON.stringify(id)}).click()`);await idle();};
  const order=()=>evaluate('[...document.querySelectorAll("#cached-list .stock-member-row")].map(row=>row.dataset.stockCode)');
  const row=code=>`.stock-member-row[data-stock-code="${code}"]`;
  const handle=code=>`.stock-drag-handle[data-stock-code="${code}"]`;
  const point=(selector,fraction=.5)=>evaluate(`(()=>{const node=document.querySelector(${JSON.stringify(selector)});const r=node.getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height*${fraction}};})()`);
  const mouse=(type,position,pressed=false)=>send('Input.dispatchMouseEvent',{type,...position,button:type==='mouseMoved'?'none':'left',buttons:pressed?1:0,clickCount:type==='mouseMoved'?0:1});
  const begin=async code=>{const origin=await point(handle(code));await mouse('mouseMoved',origin);await mouse('mousePressed',origin,true);await mouse('mouseMoved',{x:origin.x,y:origin.y+10},true);await wait('Boolean(document.querySelector(".stock-drag-preview"))');return origin;};
  const drop=async position=>{await mouse('mouseMoved',position,true);await sleep(50);await mouse('mouseReleased',position);await idle();};
  await send('Page.enable');
  await send('Emulation.setDeviceMetricsOverride',{width:1100,height:1000,deviceScaleFactor:1,mobile:false});
  await send('Page.navigate',{url:base+'/?code=000001'});await wait('typeof window.initStockPicker === "function"');await idle();
  await evaluate('document.getElementById("cached-picker").open=true');await sleep(80);await click('stock-manage');
  let initial=await order();assert.equal(initial.length,30);
  await evaluate('document.querySelector("#cached-list input").click()');
  await begin('000001');const fourth=await point(row('000004'),.8);await drop(fourth);
  let saved=await read();assert.deepEqual(saved.groups[0].codes.slice(0,5),['000002','000003','000004','000001','000005']);
  assert.deepEqual(saved.groups[1].codes,initial,'other group retains its independent order');
  assert.equal(await evaluate('document.querySelectorAll("#cached-list input:checked").length'),1,'drag preserves checkbox selection');
  assert.deepEqual(await order(),saved.groups[0].codes,'saved order renders immediately');
  await begin('000001');await drop(await point(row('000002'),.1));assert.deepEqual((await read()).groups[0].codes,initial,'dragging upward works');
  const unchanged=(await read()).groups[0].codes;
  const cancelOrigin=await begin('000002');
  await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});
  await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});
  await mouse('mouseReleased',cancelOrigin);assert.deepEqual((await read()).groups[0].codes,unchanged,'Escape cancels without saving');
  assert.equal(await evaluate('document.getElementById("cached-picker").open'),true,'Escape only cancels the drag');
  await begin('000002');await drop({x:1040,y:850});assert.deepEqual((await read()).groups[0].codes,unchanged,'drop outside the list cancels');
  assert.equal(await evaluate('document.getElementById("cached-picker").open'),true,'a cancelled drop does not click outside and close the picker');
  await evaluate(`window.dragNativeFetch=window.fetch;window.fetch=(url,options)=>url==='/api/stock-groups'&&options?.method==='POST'&&JSON.parse(options.body).action==='reorder_members'?Promise.resolve(new Response(JSON.stringify({error:'drag save failed'}),{status:400,headers:{'Content-Type':'application/json'}})):window.dragNativeFetch(url,options);`);
  await begin('000002');await drop(await point(row('000004'),.8));
  assert.deepEqual(await order(),unchanged,'failed save restores the original visible order');
  assert.match(await evaluate('document.getElementById("stock-picker-message").textContent'),/drag save failed/);
  await evaluate('window.fetch=window.dragNativeFetch;delete window.dragNativeFetch');
  await begin('000001');
  const edge=await evaluate('(()=>{const r=document.getElementById("cached-list").getBoundingClientRect();return {x:r.left+18,y:r.bottom-9};})()');
  await mouse('mouseMoved',edge,true);await wait('document.getElementById("cached-list").scrollTop>600');
  assert.ok(await evaluate('document.getElementById("cached-list").scrollTop')>500,'holding at the list edge auto-scrolls');
  const marker=await evaluate('document.querySelector(".stock-drop-before,.stock-drop-after")?.dataset.stockCode');assert.ok(Number(marker)>10,'can reach distant rows');
  await mouse('mouseReleased',edge);await idle();saved=await read();assert.ok(saved.groups[0].codes.indexOf('000001')>10,'long-distance drag is saved');
  await begin('000001');
  const topEdge=await evaluate('(()=>{const r=document.getElementById("cached-list").getBoundingClientRect();return {x:r.left+18,y:r.top+9};})()');
  await mouse('mouseMoved',topEdge,true);await wait('document.getElementById("cached-list").scrollTop===0');
  assert.equal(await evaluate('document.getElementById("cached-list").scrollTop'),0,'holding at the top edge scrolls back upward');
  await mouse('mouseReleased',topEdge);await idle();saved=await read();assert.equal(saved.groups[0].codes[0],'000001','can move a distant stock back to the first position');
  await send('Page.reload');await wait('typeof window.initStockPicker === "function"');await idle();
  await evaluate('document.getElementById("cached-picker").open=true');await sleep(80);await click('stock-manage');
  assert.deepEqual(await order(),saved.groups[0].codes,'order survives page reload');
  fs.writeFileSync(desktopImage,Buffer.from((await send('Page.captureScreenshot')).data,'base64'));
  await evaluate('document.getElementById("cached-search").value="000001";document.getElementById("cached-search").dispatchEvent(new Event("input"))');
  assert.equal(await evaluate('document.querySelectorAll(".stock-drag-handle").length'),0,'global search has no group drag handles');
  await evaluate('document.getElementById("cached-search").value="";document.getElementById("cached-search").dispatchEvent(new Event("input"));document.getElementById("cached-list").scrollTop=0');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:1000,deviceScaleFactor:1,mobile:true});
  await send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:1});await sleep(100);
  let current=await order();const origin=await point(handle(current[0])),destination=await point(row(current[3]),.8);
  await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,...origin}]});
  await send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:origin.x,y:origin.y+10}]});
  await wait('Boolean(document.querySelector(".stock-drag-preview"))');
  await send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,...destination}]});await sleep(50);
  await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await idle();
  const expected=[...current];expected.splice(3,0,expected.shift());
  assert.deepEqual((await read()).groups[0].codes,expected,'touch drag uses the same saved group order');
  const cancelTouch=await point(handle(expected[0]));
  await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,...cancelTouch}]});
  await send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:cancelTouch.x,y:cancelTouch.y+10}]});
  await wait('Boolean(document.querySelector(".stock-drag-preview"))');
  await send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});
  assert.deepEqual((await read()).groups[0].codes,expected,'pointer cancellation does not save partial order');
  assert.equal(await evaluate('Boolean(document.querySelector(".stock-drag-preview"))'),false,'cancelled touch removes its drag preview');
  assert.equal(await evaluate('document.querySelector(".cached-menu").scrollWidth<=document.querySelector(".cached-menu").clientWidth+1'),true,'mobile layout does not overflow');
  fs.writeFileSync(mobileImage,Buffer.from((await send('Page.captureScreenshot')).data,'base64'));
  console.log('drag checks passed: mouse, touch, distant auto-scroll, cancellation, save failure, independent groups, persistence');
  await send('Browser.close');socket.close();
})().catch(error=>{console.error(error);process.exit(1);});
