const assert = require('node:assert/strict');

(async () => {
  const [port,base] = process.argv.slice(2);
  const targets = await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();
  const socket = new WebSocket(targets.find(target=>target.type==='page').webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject;});
  let sequence=0;const pending=new Map(),requests=[];
  socket.onmessage=event=>{
    const message=JSON.parse(event.data),item=pending.get(message.id);
    if(item){pending.delete(message.id);message.error?item.reject(Error(message.error.message)):item.resolve(message.result);}
    if(message.method==='Network.requestWillBeSent')requests.push(message.params.request.url);
  };
  const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
  const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  const wait=async expression=>{for(let i=0;i<160;i++){if(await evaluate(expression))return;await sleep(25);}throw Error('Timed out: '+expression);};
  const idle=()=>wait('document.querySelector("#stock-groups button") && !document.getElementById("stock-manage").disabled');
  const click=async id=>{await evaluate(`document.getElementById(${JSON.stringify(id)}).click()`);await idle();};
  const read=async()=>(await fetch(base+'/api/stock-groups')).json();
  const checkCurrent=()=>evaluate('document.querySelector("#cached-list input").click()');
  await send('Page.enable');await send('Network.enable');
  await send('Emulation.setDeviceMetricsOverride',{width:1100,height:1000,deviceScaleFactor:1,mobile:false});
  await send('Page.navigate',{url:base+'/?code=000001'});await idle();
  await evaluate('document.getElementById("cached-picker").open=true');await click('stock-manage');
  await checkCurrent();await click('stock-group-remove');
  let data=await read();
  assert.equal(data.groups[0].codes.includes('000001'),false);
  assert.equal(data.groups[1].codes.includes('000001'),true);
  assert.equal(data.stocks.length,30,'removing from one group preserves all stocks');
  await evaluate('[...document.querySelectorAll("#stock-groups button")].find(button=>button.textContent.startsWith("全部股票")).click()');await idle();
  await checkCurrent();await evaluate('window.confirm=()=>false');await click('stock-unfollow');
  assert.equal((await read()).stocks.length,30,'cancelling confirmation does not unfollow');
  await evaluate('window.confirm=()=>true');await click('stock-unfollow');
  data=await read();assert.equal(data.stocks.length,29);
  assert.ok(data.groups.every(group=>!group.codes.includes('000001')));
  assert.equal(data.recent.includes('000001'),false);
  assert.equal(await evaluate('document.getElementById("full-audit").disabled'),true);
  assert.match(await evaluate('document.getElementById("prices-status").textContent'),/已取消关注/);
  assert.equal(await evaluate('document.querySelectorAll("#cached-list input:checked").length'),0);
  await evaluate('window.unfollowTestOldDocument=true');
  await send('Page.reload');await wait('!window.unfollowTestOldDocument && Boolean(document.querySelector("#stock-groups button"))');await idle();
  await wait('document.getElementById("prices-status").textContent.includes("已取消关注")');
  await click('maintenance-tab');
  await click('maintenance-stocks-tab');
  await wait('Boolean(document.querySelector("[data-unfollowed-code]"))');
  assert.match(await evaluate('document.getElementById("maintenance-unfollowed-list").textContent'),/另一分组/);
  assert.equal(await evaluate('document.getElementById("maintenance-unfollowed-list").textContent.includes("重点关注")'),false);
  await evaluate('document.getElementById("maintenance-unfollowed-search").value="无匹配";document.getElementById("maintenance-unfollowed-search").dispatchEvent(new Event("input"))');
  assert.match(await evaluate('document.getElementById("maintenance-unfollowed-list").textContent'),/没有匹配/);
  await evaluate('document.getElementById("maintenance-unfollowed-search").value="000001";document.getElementById("maintenance-unfollowed-search").dispatchEvent(new Event("input"))');
  await click('maintenance-unfollowed-select');await click('maintenance-unfollowed-restore');
  await wait('document.getElementById("maintenance-unfollowed-status").textContent.includes("已恢复关注")');
  data=await read();assert.equal(data.stocks.length,30);
  assert.equal(data.groups[0].codes.includes('000001'),false);
  assert.equal(data.groups[1].codes[0],'000001');
  assert.equal(await evaluate('document.getElementById("full-audit").disabled'),false);
  await evaluate('document.getElementById("cached-picker").open=true');await click('stock-manage');
  assert.match(await evaluate('document.getElementById("stock-results-label").textContent'),/30 只/);
  assert.equal(requests.filter(url=>/\/api\/(prices|financial|dividends|valuation|shareholders|financing)(\?|$)/.test(url)).length,0,'viewing and restoring do not request stock sources');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:1000,deviceScaleFactor:1,mobile:true});
  await click('maintenance-tab');
  assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth+1'),true,'maintenance fits mobile width');
  console.log('unfollow checks passed: group removal, cancelled confirmation, all groups, reload, maintenance search, restore, no source calls, mobile');
  await send('Browser.close');socket.close();
})().catch(error=>{console.error(error);process.exit(1);});
