const assert = require('node:assert/strict');
const fs = require('node:fs');
(async()=>{
  const [port,base,image] = process.argv.slice(2);
  const targets=await(await fetch(`http://127.0.0.1:${port}/json/list`)).json();
  const socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject;});
  let sequence=0;const pending=new Map();
  socket.onmessage=event=>{const m=JSON.parse(event.data),p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result);}};
  const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
  const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  const wait=async expression=>{for(let i=0;i<200;i++){if(await evaluate(expression))return;await sleep(25);}throw Error('Timed out: '+expression);};
  const click=id=>evaluate(`document.getElementById(${JSON.stringify(id)}).click()`);
  await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:1100,height:1000,deviceScaleFactor:1,mobile:false});
  await send('Page.navigate',{url:base+'/?code=000001'});await wait('Boolean(document.querySelector("#stock-groups button"))');
  await evaluate('window.confirm=()=>true;document.getElementById("cached-picker").open=true');await click('stock-manage');
  await evaluate('document.querySelector("#cached-list input").click()');await click('stock-unfollow');
  await wait('!document.getElementById("stock-manage").disabled && document.getElementById("prices-status").textContent.includes("已取消关注")');
  await click('maintenance-tab');
  assert.equal(await evaluate('document.getElementById("maintenance-stocks-panel").hidden'),true,'stock tools have a separate hidden tab by default');
  assert.equal(await evaluate('document.getElementById("maintenance-database-panel").hidden'),false);
  await click('maintenance-stocks-tab');await wait('Boolean(document.querySelector("[data-cleanup-code]"))');
  assert.equal(await evaluate('document.getElementById("maintenance-database-panel").hidden'),true);
  assert.equal(await evaluate('document.getElementById("maintenance-unfollowed-list").closest("[role=tabpanel]").id'), 'maintenance-stocks-panel');
  assert.equal(await evaluate('document.getElementById("maintenance-stock-cleanup").closest("[role=tabpanel]").id'), 'maintenance-stocks-panel');
  await evaluate('document.getElementById("maintenance-stocks-tab").dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowLeft",bubbles:true}))');
  assert.equal(await evaluate('document.getElementById("maintenance-database-tab").getAttribute("aria-selected")'),'true');
  await click('maintenance-stocks-tab');
  assert.deepEqual(await evaluate('[...document.querySelectorAll("#stock-cleanup-categories input:checked")].map(n=>n.value)'),['cache']);
  assert.match(await evaluate('document.getElementById("stock-cleanup-candidates").textContent'),/取消关注 0 天/);
  await evaluate('document.querySelector("[data-cleanup-code]").click()');await click('stock-cleanup-preview');
  await wait('!document.getElementById("stock-cleanup-open").hidden');
  assert.match(await evaluate('document.getElementById("stock-cleanup-detail").textContent'),/拟删除 0 条记录、1 个文件/);
  await click('stock-cleanup-open');assert.equal(await evaluate('document.getElementById("stock-cleanup-confirm").disabled'),true);
  await evaluate('document.getElementById("stock-cleanup-dialog").close()');
  const original=(await(await fetch(base+'/api/maintenance/stock-cleanup')).json()).stocks[0].summary;
  assert.equal(original.cache.files,1,'cancelling dialog does not clean');
  await evaluate('document.querySelector("#stock-cleanup-categories [value=financial]").click()');
  assert.equal(await evaluate('document.getElementById("stock-cleanup-open").hidden'),true,'scope change invalidates preview');
  await evaluate('document.querySelector("#stock-cleanup-categories [value=financial]").click()');
  await click('stock-cleanup-preview');await wait('!document.getElementById("stock-cleanup-open").hidden');await click('stock-cleanup-open');
  await evaluate('document.getElementById("stock-cleanup-word").value="清理";document.getElementById("stock-cleanup-word").dispatchEvent(new Event("input"))');
  await click('stock-cleanup-confirm');await wait('document.getElementById("stock-cleanup-status").textContent.includes("已清理 0 条记录、1 个文件")');
  await wait('!document.getElementById("stock-cleanup-refresh").disabled');
  const after=(await(await fetch(base+'/api/maintenance/stock-cleanup')).json()).stocks[0].summary;
  assert.equal(after.cache.files,0);assert.equal(after.financial.rows,original.financial.rows,'default cache cleanup preserves financial facts');
  assert.equal(await evaluate('document.getElementById("maintenance-compact-open").closest("[role=tabpanel]").id'),'maintenance-stocks-panel');
  await wait('!document.getElementById("maintenance-compact-open").disabled');
  await click('maintenance-compact-open');
  assert.equal(await evaluate('document.getElementById("maintenance-compact-confirm").disabled'),false);
  assert.equal(await evaluate('document.getElementById("maintenance-compact-dialog").querySelectorAll("input").length'),0);
  await evaluate('document.getElementById("maintenance-compact-dialog").close()');
  await click('maintenance-compact-open');
  await click('maintenance-compact-confirm');
  await wait('document.getElementById("maintenance-compact-status").textContent.includes("整理完成")');
  await wait('!document.getElementById("maintenance-compact-open").disabled');
  await click('maintenance-stocks-tab');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:1000,deviceScaleFactor:1,mobile:true});
  await evaluate('document.getElementById("maintenance-stock-cleanup").scrollIntoView()');
  assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth+1'),true,'cleanup fits mobile width');
  fs.writeFileSync(image,Buffer.from((await send('Page.captureScreenshot')).data,'base64'));
  console.log('cleanup checks passed: defaults, scope preview, confirmation, cancellation, scope invalidation, cache execution, facts retained, mobile');
  await send('Browser.close');socket.close();
})().catch(error=>{console.error(error);process.exit(1);});
