-- Full fields of Eastmoney summary reports; does not change legacy SW tables.
CREATE TABLE market_financial_batches (
 id INTEGER PRIMARY KEY, report_date TEXT NOT NULL, started_at TEXT NOT NULL,
 finished_at TEXT, status TEXT NOT NULL CHECK(status IN ('running','complete','failed')),
 result_json TEXT, error TEXT, obtained_at TEXT NOT NULL
);
CREATE INDEX market_financial_batch_period ON market_financial_batches(report_date,id);
CREATE TABLE market_financial_sources (
 id INTEGER PRIMARY KEY, batch_id INTEGER NOT NULL REFERENCES market_financial_batches(id),
 dataset TEXT NOT NULL, page_number INTEGER NOT NULL, url TEXT NOT NULL, params_json TEXT NOT NULL,
 file_path TEXT NOT NULL, content_hash TEXT NOT NULL, raw_bytes INTEGER NOT NULL, stored_bytes INTEGER NOT NULL,
 obtained_at TEXT NOT NULL, fields_json TEXT NOT NULL, UNIQUE(batch_id,dataset,page_number)
);

CREATE TABLE market_financial_income (
 id INTEGER PRIMARY KEY, exchange TEXT NOT NULL, report_date TEXT NOT NULL,
 version INTEGER NOT NULL CHECK(version>0), is_latest INTEGER NOT NULL CHECK(is_latest IN (0,1)),
 batch_id INTEGER NOT NULL REFERENCES market_financial_batches(id),
 source_id INTEGER NOT NULL REFERENCES market_financial_sources(id),
 content_hash TEXT NOT NULL, definition_version TEXT NOT NULL,
 obtained_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 secucode TEXT,
 security_code TEXT,
 industry_code TEXT,
 org_code TEXT,
 security_name_abbr TEXT,
 industry_name TEXT,
 market TEXT,
 security_type_code TEXT,
 trade_market_code TEXT,
 date_type_code TEXT,
 report_type_code TEXT,
 data_state TEXT,
 notice_date TEXT,
 source_report_date TEXT,
 parent_netprofit REAL,
 total_operate_income REAL,
 total_operate_cost REAL,
 toe_ratio REAL,
 operate_cost REAL,
 operate_expense REAL,
 operate_expense_ratio REAL,
 sale_expense REAL,
 manage_expense REAL,
 finance_expense REAL,
 operate_profit REAL,
 total_profit REAL,
 income_tax REAL,
 operate_income REAL,
 interest_ni REAL,
 interest_ni_ratio REAL,
 fee_commission_ni REAL,
 fcn_ratio REAL,
 operate_tax_add REAL,
 manage_expense_bank REAL,
 fcn_calculate REAL,
 interest_ni_calculate REAL,
 earned_premium REAL,
 earned_premium_ratio REAL,
 invest_income REAL,
 surrender_value REAL,
 compensate_expense REAL,
 toi_ratio REAL,
 operate_profit_ratio REAL,
 parent_netprofit_ratio REAL,
 deduct_parent_netprofit REAL,
 dpn_ratio REAL,
 UNIQUE(security_code,exchange,report_date,version)
);
CREATE UNIQUE INDEX market_financial_income_latest ON market_financial_income(security_code,exchange,report_date) WHERE is_latest=1;
CREATE INDEX market_financial_income_period ON market_financial_income(report_date,is_latest);

CREATE TABLE market_financial_balance (
 id INTEGER PRIMARY KEY, exchange TEXT NOT NULL, report_date TEXT NOT NULL,
 version INTEGER NOT NULL CHECK(version>0), is_latest INTEGER NOT NULL CHECK(is_latest IN (0,1)),
 batch_id INTEGER NOT NULL REFERENCES market_financial_batches(id),
 source_id INTEGER NOT NULL REFERENCES market_financial_sources(id),
 content_hash TEXT NOT NULL, definition_version TEXT NOT NULL,
 obtained_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 secucode TEXT,
 security_code TEXT,
 industry_code TEXT,
 org_code TEXT,
 security_name_abbr TEXT,
 industry_name TEXT,
 market TEXT,
 security_type_code TEXT,
 trade_market_code TEXT,
 date_type_code TEXT,
 report_type_code TEXT,
 data_state TEXT,
 notice_date TEXT,
 source_report_date TEXT,
 total_assets REAL,
 fixed_asset REAL,
 monetaryfunds REAL,
 monetaryfunds_ratio REAL,
 accounts_rece REAL,
 accounts_rece_ratio REAL,
 inventory REAL,
 inventory_ratio REAL,
 total_liabilities REAL,
 accounts_payable REAL,
 accounts_payable_ratio REAL,
 advance_receivables REAL,
 advance_receivables_ratio REAL,
 total_equity REAL,
 total_equity_ratio REAL,
 total_assets_ratio REAL,
 total_liab_ratio REAL,
 current_ratio REAL,
 debt_asset_ratio REAL,
 cash_deposit_pbc REAL,
 cdp_ratio REAL,
 loan_advance REAL,
 loan_advance_ratio REAL,
 available_sale_finasset REAL,
 asf_ratio REAL,
 loan_pbc REAL,
 loan_pbc_ratio REAL,
 accept_deposit REAL,
 accept_deposit_ratio REAL,
 sell_repo_finasset REAL,
 srf_ratio REAL,
 settle_excess_reserve REAL,
 ser_ratio REAL,
 borrow_fund REAL,
 borrow_fund_ratio REAL,
 agent_trade_security REAL,
 ats_ratio REAL,
 premium_rece REAL,
 premium_rece_ratio REAL,
 short_loan REAL,
 short_loan_ratio REAL,
 advance_premium REAL,
 advance_premium_ratio REAL,
 UNIQUE(security_code,exchange,report_date,version)
);
CREATE UNIQUE INDEX market_financial_balance_latest ON market_financial_balance(security_code,exchange,report_date) WHERE is_latest=1;
CREATE INDEX market_financial_balance_period ON market_financial_balance(report_date,is_latest);

CREATE TABLE market_financial_cashflow (
 id INTEGER PRIMARY KEY, exchange TEXT NOT NULL, report_date TEXT NOT NULL,
 version INTEGER NOT NULL CHECK(version>0), is_latest INTEGER NOT NULL CHECK(is_latest IN (0,1)),
 batch_id INTEGER NOT NULL REFERENCES market_financial_batches(id),
 source_id INTEGER NOT NULL REFERENCES market_financial_sources(id),
 content_hash TEXT NOT NULL, definition_version TEXT NOT NULL,
 obtained_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 secucode TEXT,
 security_code TEXT,
 industry_code TEXT,
 org_code TEXT,
 security_name_abbr TEXT,
 industry_name TEXT,
 market TEXT,
 security_type_code TEXT,
 trade_market_code TEXT,
 date_type_code TEXT,
 report_type_code TEXT,
 data_state TEXT,
 notice_date TEXT,
 source_report_date TEXT,
 netcash_operate REAL,
 netcash_operate_ratio REAL,
 sales_services REAL,
 sales_services_ratio REAL,
 pay_staff_cash REAL,
 psc_ratio REAL,
 netcash_invest REAL,
 netcash_invest_ratio REAL,
 receive_invest_income REAL,
 rii_ratio REAL,
 construct_long_asset REAL,
 cla_ratio REAL,
 netcash_finance REAL,
 netcash_finance_ratio REAL,
 cce_add REAL,
 cce_add_ratio REAL,
 customer_deposit_add REAL,
 cda_ratio REAL,
 deposit_iofi_other REAL,
 dio_ratio REAL,
 loan_advance_add REAL,
 laa_ratio REAL,
 receive_interest_commission REAL,
 ric_ratio REAL,
 invest_pay_cash REAL,
 ipc_ratio REAL,
 begin_cce REAL,
 begin_cce_ratio REAL,
 end_cce REAL,
 end_cce_ratio REAL,
 receive_origic_premium REAL,
 rop_ratio REAL,
 pay_origic_compensate REAL,
 poc_ratio REAL,
 UNIQUE(security_code,exchange,report_date,version)
);
CREATE UNIQUE INDEX market_financial_cashflow_latest ON market_financial_cashflow(security_code,exchange,report_date) WHERE is_latest=1;
CREATE INDEX market_financial_cashflow_period ON market_financial_cashflow(report_date,is_latest);
