-- Full ALL response of RPT_LICO_FN_CPD; leave legacy SW facts unchanged.
CREATE TABLE market_financial_performance (
 id INTEGER PRIMARY KEY, exchange TEXT NOT NULL, report_date TEXT NOT NULL,
 version INTEGER NOT NULL CHECK(version>0), is_latest INTEGER NOT NULL CHECK(is_latest IN (0,1)),
 batch_id INTEGER NOT NULL REFERENCES market_financial_batches(id),
 source_id INTEGER NOT NULL REFERENCES market_financial_sources(id),
 content_hash TEXT NOT NULL, definition_version TEXT NOT NULL,
 obtained_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 security_code TEXT,
 security_name_abbr TEXT,
 trade_market_code TEXT,
 trade_market TEXT,
 security_type_code TEXT,
 security_type TEXT,
 update_date TEXT,
 source_report_date TEXT,
 basic_eps REAL,
 deduct_basic_eps REAL,
 total_operate_income REAL,
 parent_netprofit REAL,
 weightavg_roe REAL,
 ystz REAL,
 sjltz REAL,
 bps REAL,
 mgjyxjje REAL,
 xsmll REAL,
 yshz REAL,
 sjlhz REAL,
 assigndscrpt TEXT,
 payyear TEXT,
 publishname TEXT,
 zxgxl REAL,
 notice_date TEXT,
 org_code TEXT,
 trade_market_zjg TEXT,
 isnew TEXT,
 qdate TEXT,
 datatype TEXT,
 datayear TEXT,
 datemmdd TEXT,
 eitime TEXT,
 secucode TEXT,
 board_name TEXT,
 ori_board_code TEXT,
 board_code TEXT,
 UNIQUE(security_code,exchange,report_date,version)
);
CREATE UNIQUE INDEX market_financial_performance_latest ON market_financial_performance(security_code,exchange,report_date) WHERE is_latest=1;
CREATE INDEX market_financial_performance_period ON market_financial_performance(report_date,is_latest);
